baseURL = "http://shaydul.in/hypergraph-partitioning-archive/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hypergraph Partitioning Archive"
enableRobotsTXT = true
enableEmoji = true
theme = "even"
publishDir = "docs"

paginate = 5                                             # （可选）首页显示的文章条目数量，默认为10

[author]                  # require                       # 必需
  name = "Ruslan Shaydulin"

[sitemap]                 # require                       # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "About Ruslan Shaydulin"
  weight = 50
  indentifier = "about"
  url = "http://shaydul.in"

[params]
  since = "2017"            # Site creation time          # 站点建立时间

  # site info (option)                                    # 站点信息（可选）
  logoTitle = "Hypergraph Partitioning Archive"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Multiscale", "Hypergraph","Hypergraph partitioning", "Ruslan Shaydulin", "Shaydulin"]

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目
  archive-paginate = 3

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = false

  # Some global options, you can close something in front matter.
  toc = true                                                                            # 是否开启目录
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）
  mathjax = true            # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files. # 是否在链接到markdown原始文件（如果你配置了下面的许可协议并允许hugo生成markdown文件）

  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  google_verification = ""  # Google_Verification         # 谷歌

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'


  [params.social]                                         # 社交链接
	a-email = "mailto:rshaydu@g.clemson.edu"
    # g-github = "https://github.com/rsln-s"

